name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.0 #latest version
  dio: ^4.0.6
  flutter_app_name: ^0.1.1
  flutter_easyloading: ^3.0.5
  provider: ^6.0.3
  just_audio: ^0.9.26

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter_app_name:
  name: "网易云音乐"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxIQDxUQDxIWFhUXFhASGBYVFxUXFhYWFRUWFxcZGxgYHSgiGh0nGxgYITEhJSkrLi4uGR8zODMuNygtLi0BCgoKDg0OGhAQGy0mICUtLS4tLS0tLS0tLy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAOEA4QMBIgACEQEDEQH/xAAcAAEAAgIDAQAAAAAAAAAAAAAABgcBBQMECAL/xABCEAACAQIBCQYBCgQFBQEAAAAAAQIDEQQFBhIhMUFRYXEHEyKBkaFCIzJSYnKCkqKxwRSywtE1Q1Pw8RZUY4PSM//EABsBAQADAQEBAQAAAAAAAAAAAAAEBQYDBwIB/8QANxEAAQMCAwUHBAAFBQEAAAAAAQACAwQRBSExEkFRYYEGcZGhscHREyIy8CNSYuHxJDNCcqIU/9oADAMBAAIRAxEAPwCOAAy69TQABEAARAAEQABEAARAAEQABEAARAAEQABEAARAAEQABEAARAAEQABEAARAAEQABEAARAAEQH3CDbSSbu0klrbb1JJb2Wdmn2fwglWxsVKT1ql8MftcXy2dTtDA+U2aodZXQ0jNqQ9wGp7vn/CrvAZLr4h2o0p1Psxk15vYjZ/9F4+1/wCHl+Kn+mkXdRpRhFRglFLUkkkl0SOWxYtw5lvuJWcf2lmJ+xjQOdz6ELz7jsiYmhrrUakFxcZaP4lq9zX9T0kyL5dzJwuKu1HupvXpU0km/rQ2P2fM5yYcf+B6H5Umn7SNJtOy3Nuflr4E9ypQG4zhzdr4KejWjqd9GpG7jK3B7nyfvtNOVzmlpsVo45GSND2G4O8IAD5X2gACIAAiAAIgACIAAiAAIgACIDnweEqVpqFKEpSeyMVdv+y5vUWRm72cQjapjZaT291B+Ffaktb6Ky6naKnfL+IUOsr4KRt5TnuA1PT5sq8yfk2tiJaFGnKpLelFu3V7I+Zua+YuPhDT7lPfaM4zfonr8i5sLhadKChShGEVsjFJJeSOxYsm4cy33E3Wcl7STF38NgA53J8iPJebpRabTTTTaaeppramtzPksXtYyTCLp4qKs5Nwnb4mo3UnzsmvTgV3wtxRWTxGJ5aVpaGqbVQtlblfLuI1/d4Vk9l2bys8bVV9bjST3W1OfX4V0fEso6OScGqFClRWyEIQ9Erv1O8X0MYjYGj9KwNdVOqZ3SHpyG793m5Qxc0GdeccMBR02tKcm4whe12lrbe6K39VxK1qZ/49z0u9SX0VTho+6b9znNVRxGx1Uiiwmoq2bbLAcTfPuyPjorqBXWb3aQpyVPGQUG7JVIX0fOLu7c030RYFKqppSi001dNO6a4po6xyskF2lRaqjmpXbMzbeh7itfnBk2OJw1SlNbYtxf0ZpeGS6MoD+9y689c4qeEw84aV6s4uMILatJNabW5LbzeopUrMRc0vAGoWo7NskbC8u/EkW87n0HRYABXLRIAAiAAIgACIAAiAAIgACIbfNzN+tjauhSVoq2lN/Niv3fBf8mM28hVMbXVKGpLXOW6K3vq9iW/1LuyRkynhaMaNGNor1k98m97ZNpaUynadp6qmxbFhSD6cebz4AcTz4DqctetkDIFDBU9CjHxO2lOXz5vm+HJajcgwy6a0NFhosRJI6Rxe83J3lZMMjGcmemHwd4X7yqvgg1aL+vLZHprfIrXLWeWLxN056EH8FPwq3PfLzduRGlq448tTyVlR4PU1I2rbLeJ9hqfIc1u+0/LkK0oYelJNU3Jzkta02rWT32V79eTIJCVmnwafoYbCZSyymR5eVtaOlZTRNiboN/G+pXpCnNOKa2NX9T7I/mVju/yfRm3dqKpvrT8H7J+ZIDRNcHNBG9ecSxmJ7mO1BI8MlW3a/hG1QrLYnOD6uzXsn6FaF39oWB77J1VLbC1Zfcfi/LpFI2Kavbsy34rbYBLt0Yb/ACkjxz9ysHbw2Uq9NaNKrUhyjOUV6JnUBCBsrlzQ4WIuvupNttybbe1t3b6t7T4AC/UAARAAEQABEAARAAEQABEObC4aVWcadOOlKckklvb1L/k4SyuyvIVlLG1Ft0oU7+kpf0/iO0ERleGhRK6rbSwOlPQcSdPk8rqX5sZDhgqCpRs5O0qkvpTtr8lsS4G7Bi5oWtDRYLzqSR0jy95uTmViUrK7Kxzzz6vpYfBSaWuMqq1OXFQe5fW2vdxf12j51NuWCw71LVVkvif+mnwXxenErkrKyrIOwzqVp8HwcFonnGv4tPqfYdTdZb4mAc+Ews61SNOnFuTdoxW1v/e8q9VqSbZlcJv8hZn4rGJSjT0IP453jFrkrXl5K3Mn2auYlLDKNTExjUq7bbacHyT+c/rPySJrYtIMP3yeHysxW9oQ0llML/1HToPc+C0WaWQXgaDour3l5ad9HRSbSTSV3q1G+ALJrQ0Bo0WXllfK8yPNycyVx1qanFxkk00009aaeppo0+JzTwNT52Gpr7K0P5LG8Ac1rtQkcskebHEdxI9FBcpdmuGmr0Jzpvde04+j1+5CMvZm4rCJylHTpr46d5JLmtsfS3MvExYjSUcT9BY8vhWlNjlXCfuO0OB+dfM9y82swW5nVmHTxF6mGSp1Nb0dlOo+aXzXzXmt5VWLwk6NSUKsXGSdnGW1f74lTPTvhNj4rW0OIw1jbx6jUHUfI5jrbRcAAOCnIAAiAAIgACIAAiAAIuxgcNKtVhSprXOUIx6ydvTeegMnYONGlCjD5sIxgvJber2lV9leA73GOq1qpRlJfal4Y+2l6FwFxh8dml/H0WO7R1G1M2EaNF+p+Ba3ehGs+Mu/weFcov5Sd6dPk2tcvJe9iSlKdouVf4jHTgn4KPyUeGkr6b/Fq8kd6uX6cZtqcgoOEUYqqkBw+1uZ6bupUYk+PufIBQLfr6iruyV27JJa229iSLmzGzXWCpac0nWmlpP6KevQX7ve+iIZ2YZGVbEuvNXjRs48HOV9F+STfXRLeRbUEAt9Q9Fk+0Fedr/5mHLIu58B7npwWTFwRHPLPCGDXd0kp1mr2fzYJ3s5W2vhH9Ce97WN2naLPQU8k8gjjFyf254BSbF4qFKDnVnGEVtlOSivVnJQqxnFTg04ySkmtjTV00efcqZVrYmfeV6k5S3X3cktkV0Lg7Pcd32T6d3rp6VF/c+b+VxI0FWJXloFgrOvwd1JA2Uuub2OWQ4d+ik5r8q5UpYaCqV5aMXJQ0rSaTabV7J2WrabA0WeeB7/AAFaFrtQdRdYeP8Aa3mSZCQ0ka2VXA1jpWtk/EkXtwWzwWLp1oadKcZx+lCSkvVHaPPOTMq1cNU7yhUlF3WzZJcGtjXUtfNHPOnjEqdS1Otw+GdtrhfXf6r19SNBWNk+05FWuIYJLSgvYdpo14jvHDn4qXWI5ndmzTx1LdGrFeCf9MuMX7bSSAlPYHjZdoqmGZ8LxJGbEb15yxuFnRqSpVItSi3GUXuf9t996ZwFudo+bn8RReJpR+VpLxJbZ01ra5uOtrzRUjRQVEJifbduXoOH1zayH6gyOhHA/B1HhuWAAcFOQABEAARAAEQABFa/ZLhFHDVau+dRR+7Tgre8pE9Iv2cUdHJtLn3kvztfsSg0VO3ZiaOS86xOTbrJXf1EeGXsunlXFdzQq1foU6lT8MWzzzUk3JuTu9KTb4t62/UuztEr6GTa1vi7uPk5q/tcpErsRd97W8louzcQEL5OLreAv7oAZW1dUVy0gV0dnGBVLJ8HvqOdV+b0V+WKJWa3N6CWDw8Vuo0P5EbI0sQ2WNHILzKqkMk73ne4+q1WcOU1hcNUrvXox8K4zk9GK/E0ULicRKpOVScm3JuTk9rb2stbtZrNYOnBb6qb6RhL92vQqQqsQkJkDdwC1nZ2Bracy73HyG7x9uCFj9kON8VbDt7oVY+Xhl7OHoVwSDMPHdzlCi27KUu6fSp4F76JGpn7ErSrLE4PrUkjd9rjpn/buur0PiaurPY9R9BmhXnS89ZbwboYmrS+jUlBdFJ2fmrPzOpTk004tqzTTTs01saa2MmHang9DHd4tlSnTl5xvB+0UQ0zkzdiQt4L0qjm+vAyTiB46HzBVx5h5z/xlJ06r+WppX3acdmmud9TXTiTA89ZFylPC4inXhtjJavpLY0+qui/cJiI1acakHeM4xmnykrot6OcyMsdQsdjVAKWUPjH2u8jvHx4blz2KMz3yN/CYyUIq1OXysOUZN+Hyd10sXoQLtYyepYWFdLxQnoN/Umv7qPqxWx7cV+H6UwKpMVUGbn5dd3nl1VUAAo1ukAARAAEQABEMowAivTMP/DaH2ZfzyJARbs4raWTaX1XVj+dv9yUmkhN429wXm1cCKmUH+Z3qVEO1D/Dpfbp/qymi7u0Khp5NrW+HQl5RqRv7XKRKrEf90dy1fZ0g0hHBx9AhlbV1RgEBX4XoDNqopYLDyW+jR9oJfsbQh3Znj1VwCg34qUnB9H44+0reTJiaSJ20xp5BeaVkRiqJGHc4+qg/avh3LBRmvgqa+koTj+uivMqM9DZVwMcRQnQn82cXF8Vwa5p2fkUXl3I1XCVnSrR46MktUlulF/tuKzEIiHB+5afs7VNdEac/kCSOYPxvWtPulNxkpR3OLXVO69z5tyJjmBmvPEVoYitFqjTkpJtW7yUXeKjxjezb2arcbQomOkdstV5U1DKeIyyaDzPDndW9SbaTe2yuchhGTSLzNVp2wxV8M9/y68vB+5WxOO1jGKeLhSX+XTV/tTd2vRR9SDlBWEGZ1l6Dg7C2ijB4E+JJHkhcvZnje9yfGLd3TnKn5WjNeilbyKaLR7IJ/I148J05eqkv6UdKA2mtxBUfH2B1GTwIPt7qwzS534bvcn4iP8A45TXWHjXvE3R08qxvh6q406q9YsuXi7SFion7EjXDcQV54Zgy9vmzBmV6g7IlAAF+IAAiAAIgACK1uyXF6WFq0b64VFL7tSCt7wkT4p7styh3eNdNvVVi4r7S8Ufa/qXCX1E/ahHLJYLG4fp1rzudY+OvnddPKmFVahVpfThUh+KLR56qQcZOMlbxSTXBrU/c9IlKdo2Su4x0ppeCt8rHhpO+mvxfqjhiMd2h/BT+zdQGyPhO/Md418j5KLAAqFrlJ8wMvLCYpKo7UqtoSe6Lv4X5NtPlJ8C7EebUWPmJnolGOFxcrWtGnUlstujN7uCfk+dlQ1Ib/Dd0Wax3DXSf6iIXIH3DeQN47hkeVuCsw6uMwdOrDRq04zjwnFSXozsoyWxCyQJGYWjoZrYKEtKOGp32q60kuid0jdRVtSPoH4GgaL6fI95u8k95uh0Mr5Rp4ahOvUfhgr829iiubdl5n3jsdToU3UrTUIR2t/pzfJFPZ6Z1yx09CF40YPwp7W9mk+fBbvM4VFQ2JvPcFOw3Dn1kltGjU+w5ny1K0WUsZKvWnWntnKcnyu9SXJKyXJHVAKAm5uV6CAGgAaBC1eyKlbDVZ8akYfhgn/UVUXf2f4F0cnUr7Z3qv7+uP5dEm4e28t+AVJ2gkDaTZ/mIHhn8KSnQy1U0cLWlwpVX6QZ3yO5+YvucnV5LbKKpr/2NRfs2W8h2Wk8isbTx/UlYwbyB4lUdbb1ZgyYM0vTybm6AAL8QABEAARAAEXYwOJlSqwq09sJQlHrF39D0Bk7GRrUYVofNnGM15rZ1Ww87lldlWXLqWDqPjOnf88f6vxE+glDXlp3+qoO0FIZYBM3Vmvcfg5+KsojWfOQv4zCtRXykPlKfNpeKPmvdIkpgt3sD2lp3rIQzPhkbIzUG683Nbj5LC7R81dFyxlCPhk71Ir4JP8AzOj38Hr3u1ememiMT9kr0Wkq2VUQlZ1HA8D+5hDJgHJSVI8gZ5YnCJQjLvIL4J3aS+q9semzkTLBdp1BpKtRqRe9wcJx92n7FVAkx1crBYHJV1RhNJUHae3PiMv7eIuril2jYFLV3j5KC/eSRpso9p+q2Goa+NVrV92L1/iK2B9urpjyXCPAaJhuWk95+LfHJbHK+Wq+LnpV6kpcFsiuiWqPXaa4AiEkm5VsxjWNDWiwG4ZBAD6UW3ZJtuySWttvYkt7PxfS2ma+R3i8VCkvm3vN8IRtpP8AtzaL6pU1FKMVZJJJcEthGMxM3Fg6GlNfKzs5fVS+bDy2vm+SJWXtHD9JmepWDxmuFVPZh+1uQ5nefbuAQrjtbyjaFLDJ7W6suiUoRv1bl+EsKtUUYuUmkkm23sSWtsobOfKrxeLnV3XtBcILUvbX1bPmuk2Y9neV1wCmMtV9TczProPnotSACkW3QABEAARAAEQABEObCYmdKpGrTejKMlJPg1/vYcIANkIBFir7zZy1DG4eNaGp/NnH6M1tXTeuTNyULmvl+eBrKpHXB2jUhukv2a2p/wBy7MmZRp4mlGrRlpRlv3p701ua3ovqWoErc9d/ysDiuGmkku38DoeHI+3Ec7rtTgpJpq6d009jTKsz1zHdJyxGDi3T1uVNa5Q2t6K3w5bV02WuYZ1mhbK2zlGoq6Wkk24+o3H93HcvNt+JguTOPMWhim50/kaj13iloSf1lufNW8yt8sZqYvCt95Tbj/qQ8cfVa195IpZqWSPUXHEfuS2tHi1NVCwOy7gfY6H14gLRgzrW1GCMrPRAAF+ID6jBt2UW29iWtvyJRkbMTF4hpzh3UONS6duUdr87H2yNzzZouuM9RFA3alcGjn7bz0uVGKVJykoxTbbsoxTbbe5JbWWtmPmWsNbEYlJ1dsY6mqd7a3xn7L3N1m9mth8Er01pVLWdSeuXRborkvO5IEW1NRhh2n6+iyWJ42ZwYoMm7ydT8DzKGQR7OzOKGBo6WqVWV1Thxf0nwit/oTXuDRtHRUcUT5XiNguToFH+07OLu6f8JSfjmk6jW6G6PWX6dSrDmxeInVqSqTk3JtylJ7W2cJn6iYyv2ivQ6CjbSQiIa6k8T+5D/KAA4qYgACIAAiAAIgACIAAiG8zWzlq4CreHihK2nTb1S5rg+fqaMH0x5Ydpuq+JYmSsLHi4OoV/5Cy3SxlPToyvulF6pxfCS3ddj3G1POuTsoVcPUVShNxkt63rg1sa5MszN3tFpVbU8Wu7ns01d05dd8Pdcy4grWvyfkfJY2vwKWEl0P3N/wDQ+e8dVPjDOKhVjOKlCSlF604tNPo0cxOVCtPj82sJXu6uHg2/iS0ZfijZmlq9nGBls72PSSf88WTIHN0MbtWhSoq2piFmSOA7yoQuzTB76lZ/ep//AAdzD5gYCDu6Up/bnK3pGyJWD5FPENGjwXR2JVjtZXeJXQwGS6FBWo0acPsxSfrtZ3wDqABkFCJLjcm6A6eUMoUqENOtOMI8ZO1+SW98kV7nH2juSdPAxa2rvZrxfdju6y9DnLOyIXcem9S6ShnqnWiblxOQHX2FzyUpzqzro4KLjdSrNXjTW7g5/Rj7vcU5lXKNXE1ZVa0rye/cluVtyXA61Wq5ScpNyle7lJttvi29rPgpaipdMeXBbXDsMio25ZuOp9hwHr5AACMrJAAEQABEAARAAEQABEAARAAEQABFsMl5ZxGFlpUKso73Z6n1T1P0Jjk7tOqxssRRjPnBuEvR3T9UV8DtHPJH+JUSooKaozlYCeOh8RY+KuTCdomBmvFKdN8Jxv7wubWlnXgpbMTTX2no/wA1ihjNyS3EZBqAVVv7OUx/Fzh1B9lff/U+C/7ql+OJ1MTnrgYf56l9mM5foij7g/TiL9zQvhvZun3vcfAexVs4ztLwsf8A8qdWo+Noxj6tt+xGspdpOKqpqlGNJcY+Kf4pavykKBxfWSu327lOhwWjiz2L/wDY38tPJdjGYyrWnp1pym/pSbk/fYuR1wCMTdWgFhYIAD8RAAEQABEAARAAEQABEAARAAEQABEAARAAEQABEAARAAEQABEAARAAEQABEAARAAEQABEAARAAEQABEAARAAEQABEAARAAEQABEAARAAEQABEAARAAEX//2Q=="

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/anim/
    - assets/anim/loading/
    - assets/intell/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
